POST http://localhost:3000/addcategory.test.php
Content-Type: application/x-www-form-urlencoded

categoryID=___
&categoryCode=___
&categoryName=___
###
GET http://localhost:3000/listcategories.test.php
###
POST http://localhost:3000/changecategory.test.php
Content-Type: application/x-www-form-urlencoded

categoryID=___
&categoryCode=___
&categoryName=___
###
POST http://localhost:3000/removecategory.test.php
Content-Type: application/x-www-form-urlencoded

categoryID=___